export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST';
export const QUESTION_LIST_SUCCESS = 'QUESTION_LIST_SUCCESS';
export const QUESTION_LIST_FAIL = 'QUESTION_LIST_FAIL';

export const QUESTION_SAVE_REQUEST = 'QUESTION_SAVE_REQUEST';
export const QUESTION_SAVE_SUCCESS = 'QUESTION_SAVE_SUCCESS';
export const QUESTION_SAVE_FAIL = 'QUESTION_SAVE_FAIL';

export const QUESTION_DETAILS_REQUEST = 'QUESTION_DETAILS_REQUEST';
export const QUESTION_DETAILS_SUCCESS = 'QUESTION_DETAILS_SUCCESS';
export const QUESTION_DETAILS_FAIL = 'QUESTION_DETAILS_FAIL';

export const ANSWER_SAVE_REQUEST = 'ANSWER_SAVE_REQUEST';
export const ANSWER_SAVE_SUCCESS = 'ANSWER_SAVE_SUCCESS';
export const ANSWER_SAVE_FAIL = 'ANSWER_SAVE_FAIL';
export const ANSWER_SAVE_RESET = 'ANSWER_SAVE_RESET';

export const ANSWER_LIST_REQUEST = 'ANSWER_LIST_REQUEST';
export const ANSWER_LIST_SUCCESS = 'ANSWER_LIST_SUCCESS';
export const ANSWER_LIST_FAIL = 'ANSWER_LIST_FAIL';



